// api/Tours/template?templateId=1E78A063-7506-4DE3-BA46-08FAEA8EE879
export default [
  {
    "<Id>k__BackingField": "b1f87121-6cf3-431b-bb06-fa8bb6991eea",
    "<Name>k__BackingField": "MSCINVisible",
    "<Steps>k__BackingField": [
      {
        "<Id>k__BackingField": "681fc52f-d683-496d-8711-c067914df299",
        "<Name>k__BackingField": "Page - bar - New step",
        "<PageTitle>k__BackingField": null,
        "<Height>k__BackingField": 0,
        "<Width>k__BackingField": 0,
        "<MeasuredWidth>k__BackingField": 200,
        "<MeasuredHeight>k__BackingField": 100,
        "<HtmlContent>k__BackingField": "<p>sdasd</p>",
        "<StartUpScript>k__BackingField": null,
        "<Index>k__BackingField": 1,
        "<PageId>k__BackingField": "8591f405-edad-46f5-a297-fc54c5d72cb3",
        "<Orientation>k__BackingField": 0,
        "<TourId>k__BackingField": "b1f87121-6cf3-431b-bb06-fa8bb6991eea",
        "<TargetId>k__BackingField": null,
        "<VisualId>k__BackingField": "5e970265-383b-4633-a6b0-f83781af6407",
        "<TargetType>k__BackingField": 2,
        "<CustomStyle>k__BackingField": null,
        "<GuideId>k__BackingField": null,
        "<Title>k__BackingField": "New step",
        "<StyleId>k__BackingField": "00000000-0000-0000-0000-000000000000",
        "<CustomTargetId>k__BackingField": null,
        "<SubVisuals>k__BackingField": null,
        "<Validation>k__BackingField": null,
        "<IsToolTip>k__BackingField": false
      }
    ],
    "<StepCount>k__BackingField": 1,
    "<Type>k__BackingField": "Shortcuts",
    "<CountWrongAnswers>k__BackingField": 0,
    "<LastOpenDate>k__BackingField": "1900-01-01T00:00:00",
    "<TotalVisits>k__BackingField": 0,
    "<Visibility>k__BackingField": "Only me"
  },
  {
    "<Id>k__BackingField": "64606c4a-f650-430c-a446-b450a04c7cca",
    "<Name>k__BackingField": "MSCVisible",
    "<Steps>k__BackingField": [
      {
        "<Id>k__BackingField": "c5447c2f-6a26-4e16-8a86-6c7b4e5ee9d6",
        "<Name>k__BackingField": "Page - Box Plot - New step",
        "<PageTitle>k__BackingField": null,
        "<Height>k__BackingField": 0,
        "<Width>k__BackingField": 0,
        "<MeasuredWidth>k__BackingField": 200,
        "<MeasuredHeight>k__BackingField": 100,
        "<HtmlContent>k__BackingField": "<p>sde</p>",
        "<StartUpScript>k__BackingField": null,
        "<Index>k__BackingField": 1,
        "<PageId>k__BackingField": "8591f405-edad-46f5-a297-fc54c5d72cb3",
        "<Orientation>k__BackingField": 0,
        "<TourId>k__BackingField": "64606c4a-f650-430c-a446-b450a04c7cca",
        "<TargetId>k__BackingField": null,
        "<VisualId>k__BackingField": "5b67a8f6-e164-433f-a1ff-883b17e901d8",
        "<TargetType>k__BackingField": 2,
        "<CustomStyle>k__BackingField": null,
        "<GuideId>k__BackingField": null,
        "<Title>k__BackingField": "New step",
        "<StyleId>k__BackingField": "00000000-0000-0000-0000-000000000000",
        "<CustomTargetId>k__BackingField": null,
        "<SubVisuals>k__BackingField": null,
        "<Validation>k__BackingField": null,
        "<IsToolTip>k__BackingField": false
      }
    ],
    "<StepCount>k__BackingField": 1,
    "<Type>k__BackingField": "Shortcuts",
    "<CountWrongAnswers>k__BackingField": 0,
    "<LastOpenDate>k__BackingField": "1900-01-01T00:00:00",
    "<TotalVisits>k__BackingField": 0,
    "<Visibility>k__BackingField": "Everyone"
  },
  {
    "<Id>k__BackingField": "ed7931b4-16cc-452d-8214-4264568fd7db",
    "<Name>k__BackingField": "MTooltipINVisible",
    "<Steps>k__BackingField": [
      {
        "<Id>k__BackingField": "42b7b7eb-9394-4a55-a36e-b77ae3519c4e",
        "<Name>k__BackingField": "Page - manyblocks - New step",
        "<PageTitle>k__BackingField": null,
        "<Height>k__BackingField": 0,
        "<Width>k__BackingField": 0,
        "<MeasuredWidth>k__BackingField": 200,
        "<MeasuredHeight>k__BackingField": 100,
        "<HtmlContent>k__BackingField": "<p>asdasd</p>",
        "<StartUpScript>k__BackingField": null,
        "<Index>k__BackingField": 1,
        "<PageId>k__BackingField": "8591f405-edad-46f5-a297-fc54c5d72cb3",
        "<Orientation>k__BackingField": 0,
        "<TourId>k__BackingField": "ed7931b4-16cc-452d-8214-4264568fd7db",
        "<TargetId>k__BackingField": null,
        "<VisualId>k__BackingField": "5ec29612-259e-44d4-8c7c-43ed7b921253",
        "<TargetType>k__BackingField": 2,
        "<CustomStyle>k__BackingField": null,
        "<GuideId>k__BackingField": null,
        "<Title>k__BackingField": "New step",
        "<StyleId>k__BackingField": "00000000-0000-0000-0000-000000000000",
        "<CustomTargetId>k__BackingField": null,
        "<SubVisuals>k__BackingField": null,
        "<Validation>k__BackingField": null,
        "<IsToolTip>k__BackingField": true
      }
    ],
    "<StepCount>k__BackingField": 1,
    "<Type>k__BackingField": "TitleButtons",
    "<CountWrongAnswers>k__BackingField": 0,
    "<LastOpenDate>k__BackingField": "1900-01-01T00:00:00",
    "<TotalVisits>k__BackingField": 0,
    "<Visibility>k__BackingField": "Only me"
  },
  {
    "<Id>k__BackingField": "4a7ea835-6dc4-4792-8700-a6af9317d6a1",
    "<Name>k__BackingField": "MTooltipVisible",
    "<Steps>k__BackingField": [
      {
        "<Id>k__BackingField": "490a7dee-60ee-48b3-a66c-2f1a2511bbf2",
        "<Name>k__BackingField": "Page (Page)  - New step",
        "<PageTitle>k__BackingField": null,
        "<Height>k__BackingField": 0,
        "<Width>k__BackingField": 0,
        "<MeasuredWidth>k__BackingField": 200,
        "<MeasuredHeight>k__BackingField": 100,
        "<HtmlContent>k__BackingField": "<p>adasd</p>",
        "<StartUpScript>k__BackingField": null,
        "<Index>k__BackingField": 1,
        "<PageId>k__BackingField": "8591f405-edad-46f5-a297-fc54c5d72cb3",
        "<Orientation>k__BackingField": 0,
        "<TourId>k__BackingField": "4a7ea835-6dc4-4792-8700-a6af9317d6a1",
        "<TargetId>k__BackingField": null,
        "<VisualId>k__BackingField": null,
        "<TargetType>k__BackingField": 1,
        "<CustomStyle>k__BackingField": null,
        "<GuideId>k__BackingField": null,
        "<Title>k__BackingField": "New step",
        "<StyleId>k__BackingField": "00000000-0000-0000-0000-000000000000",
        "<CustomTargetId>k__BackingField": null,
        "<SubVisuals>k__BackingField": null,
        "<Validation>k__BackingField": null,
        "<IsToolTip>k__BackingField": true
      }
    ],
    "<StepCount>k__BackingField": 1,
    "<Type>k__BackingField": "TitleButtons",
    "<CountWrongAnswers>k__BackingField": 0,
    "<LastOpenDate>k__BackingField": "1900-01-01T00:00:00",
    "<TotalVisits>k__BackingField": 0,
    "<Visibility>k__BackingField": "Everyone"
  },
  {
    "<Id>k__BackingField": "54830777-0a27-412a-85f2-d4349dd96b08",
    "<Name>k__BackingField": "MTourINVisible",
    "<Steps>k__BackingField": [
      {
        "<Id>k__BackingField": "b90d868e-910d-492a-add5-a4533079cd18",
        "<Name>k__BackingField": "Page - bar - asd",
        "<PageTitle>k__BackingField": null,
        "<Height>k__BackingField": 0,
        "<Width>k__BackingField": 0,
        "<MeasuredWidth>k__BackingField": 200,
        "<MeasuredHeight>k__BackingField": 100,
        "<HtmlContent>k__BackingField": "<p>asdasd</p>",
        "<StartUpScript>k__BackingField": null,
        "<Index>k__BackingField": 2,
        "<PageId>k__BackingField": "8591f405-edad-46f5-a297-fc54c5d72cb3",
        "<Orientation>k__BackingField": 0,
        "<TourId>k__BackingField": "54830777-0a27-412a-85f2-d4349dd96b08",
        "<TargetId>k__BackingField": null,
        "<VisualId>k__BackingField": "5e970265-383b-4633-a6b0-f83781af6407",
        "<TargetType>k__BackingField": 2,
        "<CustomStyle>k__BackingField": null,
        "<GuideId>k__BackingField": null,
        "<Title>k__BackingField": "asd",
        "<StyleId>k__BackingField": "00000000-0000-0000-0000-000000000000",
        "<CustomTargetId>k__BackingField": null,
        "<SubVisuals>k__BackingField": null,
        "<Validation>k__BackingField": null,
        "<IsToolTip>k__BackingField": false
      },
      {
        "<Id>k__BackingField": "06208ede-0fdd-4723-b60e-a795683951b3",
        "<Name>k__BackingField": "Page - blocks - New step",
        "<PageTitle>k__BackingField": null,
        "<Height>k__BackingField": 0,
        "<Width>k__BackingField": 0,
        "<MeasuredWidth>k__BackingField": 200,
        "<MeasuredHeight>k__BackingField": 100,
        "<HtmlContent>k__BackingField": "<p>asedsd</p>",
        "<StartUpScript>k__BackingField": null,
        "<Index>k__BackingField": 1,
        "<PageId>k__BackingField": "8591f405-edad-46f5-a297-fc54c5d72cb3",
        "<Orientation>k__BackingField": 0,
        "<TourId>k__BackingField": "54830777-0a27-412a-85f2-d4349dd96b08",
        "<TargetId>k__BackingField": null,
        "<VisualId>k__BackingField": "d3fff50f-8c0e-4ac0-894c-1b746366a835",
        "<TargetType>k__BackingField": 2,
        "<CustomStyle>k__BackingField": null,
        "<GuideId>k__BackingField": null,
        "<Title>k__BackingField": "New step",
        "<StyleId>k__BackingField": "00000000-0000-0000-0000-000000000000",
        "<CustomTargetId>k__BackingField": null,
        "<SubVisuals>k__BackingField": null,
        "<Validation>k__BackingField": null,
        "<IsToolTip>k__BackingField": false
      }
    ],
    "<StepCount>k__BackingField": 2,
    "<Type>k__BackingField": "Tour",
    "<CountWrongAnswers>k__BackingField": 0,
    "<LastOpenDate>k__BackingField": "2017-11-01T16:00:33.023",
    "<TotalVisits>k__BackingField": 3,
    "<Visibility>k__BackingField": "Only me"
  },
  {
    "<Id>k__BackingField": "914bab47-b91d-4c60-873d-1074dc00bd83",
    "<Name>k__BackingField": "MTourVisible",
    "<Steps>k__BackingField": [
      {
        "<Id>k__BackingField": "27183556-ae1d-4df5-a0f5-2348ad380b03",
        "<Name>k__BackingField": "Page (Page)  - New step",
        "<PageTitle>k__BackingField": null,
        "<Height>k__BackingField": 0,
        "<Width>k__BackingField": 0,
        "<MeasuredWidth>k__BackingField": 200,
        "<MeasuredHeight>k__BackingField": 100,
        "<HtmlContent>k__BackingField": "<p>asdasd</p>",
        "<StartUpScript>k__BackingField": null,
        "<Index>k__BackingField": 1,
        "<PageId>k__BackingField": "8591f405-edad-46f5-a297-fc54c5d72cb3",
        "<Orientation>k__BackingField": 0,
        "<TourId>k__BackingField": "914bab47-b91d-4c60-873d-1074dc00bd83",
        "<TargetId>k__BackingField": null,
        "<VisualId>k__BackingField": null,
        "<TargetType>k__BackingField": 1,
        "<CustomStyle>k__BackingField": null,
        "<GuideId>k__BackingField": null,
        "<Title>k__BackingField": "New step",
        "<StyleId>k__BackingField": "00000000-0000-0000-0000-000000000000",
        "<CustomTargetId>k__BackingField": null,
        "<SubVisuals>k__BackingField": null,
        "<Validation>k__BackingField": null,
        "<IsToolTip>k__BackingField": false
      },
      {
        "<Id>k__BackingField": "87f2d6ca-15e7-455f-9aae-f58fb0dbc5da",
        "<Name>k__BackingField": "Page - manyblocks - ad",
        "<PageTitle>k__BackingField": null,
        "<Height>k__BackingField": 0,
        "<Width>k__BackingField": 0,
        "<MeasuredWidth>k__BackingField": 200,
        "<MeasuredHeight>k__BackingField": 100,
        "<HtmlContent>k__BackingField": "<p>asdasd</p>",
        "<StartUpScript>k__BackingField": null,
        "<Index>k__BackingField": 2,
        "<PageId>k__BackingField": "8591f405-edad-46f5-a297-fc54c5d72cb3",
        "<Orientation>k__BackingField": 0,
        "<TourId>k__BackingField": "914bab47-b91d-4c60-873d-1074dc00bd83",
        "<TargetId>k__BackingField": null,
        "<VisualId>k__BackingField": "5ec29612-259e-44d4-8c7c-43ed7b921253",
        "<TargetType>k__BackingField": 2,
        "<CustomStyle>k__BackingField": null,
        "<GuideId>k__BackingField": null,
        "<Title>k__BackingField": "ad",
        "<StyleId>k__BackingField": "00000000-0000-0000-0000-000000000000",
        "<CustomTargetId>k__BackingField": null,
        "<SubVisuals>k__BackingField": null,
        "<Validation>k__BackingField": null,
        "<IsToolTip>k__BackingField": false
      }
    ],
    "<StepCount>k__BackingField": 2,
    "<Type>k__BackingField": "Tour",
    "<CountWrongAnswers>k__BackingField": 0,
    "<LastOpenDate>k__BackingField": "2017-11-01T16:01:30.007",
    "<TotalVisits>k__BackingField": 3,
    "<Visibility>k__BackingField": "Everyone"
  },
  {
    "<Id>k__BackingField": "087ec0bc-166d-465d-8fc6-0b7884c71b1b",
    "<Name>k__BackingField": "nurzhan tour all",
    "<Steps>k__BackingField": [
      {
        "<Id>k__BackingField": "1b00bf32-31fd-4345-8595-3c483b139dc7",
        "<Name>k__BackingField": "Page (Page)  - New step",
        "<PageTitle>k__BackingField": null,
        "<Height>k__BackingField": 0,
        "<Width>k__BackingField": 0,
        "<MeasuredWidth>k__BackingField": 200,
        "<MeasuredHeight>k__BackingField": 100,
        "<HtmlContent>k__BackingField": "<p>ddd</p>",
        "<StartUpScript>k__BackingField": null,
        "<Index>k__BackingField": 1,
        "<PageId>k__BackingField": "8591f405-edad-46f5-a297-fc54c5d72cb3",
        "<Orientation>k__BackingField": 0,
        "<TourId>k__BackingField": "087ec0bc-166d-465d-8fc6-0b7884c71b1b",
        "<TargetId>k__BackingField": null,
        "<VisualId>k__BackingField": null,
        "<TargetType>k__BackingField": 1,
        "<CustomStyle>k__BackingField": null,
        "<GuideId>k__BackingField": null,
        "<Title>k__BackingField": "New step",
        "<StyleId>k__BackingField": "00000000-0000-0000-0000-000000000000",
        "<CustomTargetId>k__BackingField": null,
        "<SubVisuals>k__BackingField": null,
        "<Validation>k__BackingField": null,
        "<IsToolTip>k__BackingField": false
      }
    ],
    "<StepCount>k__BackingField": 1,
    "<Type>k__BackingField": "Tour",
    "<CountWrongAnswers>k__BackingField": 0,
    "<LastOpenDate>k__BackingField": "2017-11-01T15:55:36.907",
    "<TotalVisits>k__BackingField": 1,
    "<Visibility>k__BackingField": "Everyone"
  },
  {
    "<Id>k__BackingField": "51e78df8-4e36-4faa-969b-846f3681143f",
    "<Name>k__BackingField": "nurzhan tour only me",
    "<Steps>k__BackingField": [
      {
        "<Id>k__BackingField": "2274290f-3f02-4ec4-a47e-2e886d1b39c8",
        "<Name>k__BackingField": "Page (Page)  - New step",
        "<PageTitle>k__BackingField": null,
        "<Height>k__BackingField": 0,
        "<Width>k__BackingField": 0,
        "<MeasuredWidth>k__BackingField": 200,
        "<MeasuredHeight>k__BackingField": 100,
        "<HtmlContent>k__BackingField": "<p>fv</p>",
        "<StartUpScript>k__BackingField": null,
        "<Index>k__BackingField": 1,
        "<PageId>k__BackingField": "8591f405-edad-46f5-a297-fc54c5d72cb3",
        "<Orientation>k__BackingField": 0,
        "<TourId>k__BackingField": "51e78df8-4e36-4faa-969b-846f3681143f",
        "<TargetId>k__BackingField": null,
        "<VisualId>k__BackingField": null,
        "<TargetType>k__BackingField": 1,
        "<CustomStyle>k__BackingField": null,
        "<GuideId>k__BackingField": null,
        "<Title>k__BackingField": "New step",
        "<StyleId>k__BackingField": "00000000-0000-0000-0000-000000000000",
        "<CustomTargetId>k__BackingField": null,
        "<SubVisuals>k__BackingField": null,
        "<Validation>k__BackingField": null,
        "<IsToolTip>k__BackingField": false
      }
    ],
    "<StepCount>k__BackingField": 1,
    "<Type>k__BackingField": "Tour",
    "<CountWrongAnswers>k__BackingField": 0,
    "<LastOpenDate>k__BackingField": "1900-01-01T00:00:00",
    "<TotalVisits>k__BackingField": 0,
    "<Visibility>k__BackingField": "Only me"
  }
]
